"""Tests for Atlas agent report workers."""

import json
from pathlib import Path

import pytest

from src import atlas_agents, atlas_config


@pytest.fixture
def atlas_data_dir(tmp_path, monkeypatch):
    data_dir = tmp_path / "data" / "atlas"
    defaults_dir = tmp_path / "config" / "atlas"
    defaults_dir.mkdir(parents=True)
    data_dir.mkdir(parents=True)

    for name in ("agents.json", "reports.json", "aurelius_profile.json", "projects.json", "atlas_identity.json"):
        src = Path(__file__).resolve().parents[1] / "config" / "atlas" / name
        if src.exists():
            (defaults_dir / name).write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
            (data_dir / name).write_text(src.read_text(encoding="utf-8"), encoding="utf-8")

    monkeypatch.setattr(atlas_config, "_DATA_DIR", data_dir)
    monkeypatch.setattr(atlas_config, "_DEFAULTS_DIR", defaults_dir)
    return data_dir


@pytest.mark.asyncio
async def test_run_agent_action_fallback_without_llm(atlas_data_dir, monkeypatch):
    def _no_llm(owner):
        return None, None, None

    monkeypatch.setattr(atlas_agents, "_resolve_llm", _no_llm)

    result = await atlas_agents.run_agent_action("research", "research_brief", owner="testuser")

    assert result["ok"] is True
    assert result["completed"] is True
    assert result["used_llm"] is False
    report = result["report"]
    assert report["agent_id"] == "research"
    assert report["status"] == "waiting_for_review"
    assert report["content"]
    assert report["summary"]

    reports = atlas_config.load_reports()
    assert len(reports) == 1
    assert reports[0]["id"] == report["id"]

    agents = atlas_config.load_agents()
    research = next(a for a in agents if a["id"] == "research")
    assert research["status"] == "waiting"
    assert research["waiting_on"] == "User review"
    assert report["id"] in research["report_history"]


@pytest.mark.asyncio
async def test_run_agent_action_uses_llm_when_available(atlas_data_dir, monkeypatch):
    def _fake_llm(owner):
        return "http://localhost/v1/chat/completions", "test-model", {}

    async def _fake_call(owner, system, user_prompt, **kwargs):
        return "# LLM Report\n\nGenerated by test."

    monkeypatch.setattr(atlas_agents, "_resolve_llm", _fake_llm)
    monkeypatch.setattr(atlas_agents, "_call_llm", _fake_call)

    result = await atlas_agents.run_agent_action("business", "business_strategy", owner="testuser")

    assert result["ok"] is True
    assert result["used_llm"] is True
    assert "LLM Report" in result["report"]["content"]


def test_apply_report_action_approve(atlas_data_dir):
    report = {
        "id": "r1",
        "agent_id": "research",
        "agent_name": "Research Agent",
        "title": "Test",
        "status": "waiting_for_review",
        "created_at": "2026-06-06T12:00:00+00:00",
        "summary": "Test summary",
        "content": "Body",
        "actions": ["approve", "revise", "archive"],
    }
    atlas_config.save_reports([report])

    result = atlas_agents.apply_report_action("r1", "approve")
    assert result["ok"] is True
    assert result["report"]["status"] == "approved"

    agents = atlas_config.load_agents()
    research = next(a for a in agents if a["id"] == "research")
    assert research["waiting_on"] is None
    assert research["status"] == "idle"


def test_normalize_action_aliases():
    assert atlas_agents.normalize_action("business_ask") == "business_strategy"
    assert atlas_agents.normalize_action("sync") == "sync_agents"


def test_reports_for_queue_buckets(atlas_data_dir):
    today = atlas_agents._today_utc()
    atlas_config.save_reports([
        {"id": "1", "status": "waiting_for_review", "created_at": f"{today}T10:00:00+00:00"},
        {"id": "2", "status": "approved", "created_at": f"{today}T11:00:00+00:00"},
        {"id": "3", "status": "revision_requested", "created_at": f"{today}T09:00:00+00:00"},
    ])
    queue = atlas_agents.reports_for_queue()
    assert len(queue["waiting_for_approval"]) == 1
    assert len(queue["completed_today"]) == 1
    assert len(queue["pending"]) == 1
